'use strict';

// ============================================================
// THEMES — single source of truth for the desktop injector.
//
// The browser userscript (tana-themer.user.js) embeds its own
// copy of this data. If you add or edit a theme here, paste the
// same change into the THEMES object in tana-themer.user.js too.
// ============================================================

const THEMES = {

  'tana-light': {
    id: 'tana-light', name: 'Tana Light', mode: 'light',
    preview: ['#ffffff', '#297dd9', '#33343e'], vars: {},
  },

  'tana-dark': {
    id: 'tana-dark', name: 'Tana Dark', mode: 'dark',
    preview: ['#1c1d22', '#297dd9', '#c9c8d4'], vars: {},
  },

  'nord': {
    id: 'nord', name: 'Nord', mode: 'dark',
    preview: ['#2e3440', '#88c0d0', '#d8dee9'],
    vars: {
      '--colorPanelBackground':                '#2e3440',
      '--colorPanelBackgroundDimmed':          '#3b4252',
      '--colorPanelBackgroundHighlighted':     '#434c5e',
      '--colorPanelBackgroundTransparent':     'rgba(46,52,64,0)',
      '--colorNavigationAltPanelBackground':   '#3b4252',
      '--colorUIContextMenuBackground':        '#3b4252',
      '--colorCanvasBackground':               '#272c36',
      '--colorEditorText':                     '#d8dee9',
      '--colorEditorTextHighlight':            '#eceff4',
      '--colorEditorTextMuted':                '#8b98b3',
      '--colorUIText':                         '#9aa8c0',
      '--colorUITextMuted':                    '#6d7a90',
      '--colorUITextDisabled':                 '#4f5a6b',
      '--colorUITextOnHighlight':              '#eceff4',
      '--colorLink':                           '#88c0d0',
      '--colorLinkMuted':                      '#81a1c1',
      '--colorHoverLink':                      '#eceff4',
      '--colorFocus':                          '#88c0d0',
      '--colorFocusInactive':                  '#4c566a',
      '--colorFocusWithin':                    '#5e81ac',
      '--colorFocusText':                      '#81a1c1',
      '--colorSelected':                       '#3b4252',
      '--colorSelectedUnfocused':              '#434c5e',
      '--colorTextSelectedUnfocused':          '#4c566a',
      '--colorTextHighlightedBackground':      '#3d4a5c',
      '--colorUIStroke':                       '#4c566a',
      '--colorUIStrokeSoft':                   '#3b4252',
      '--colorUIStrokeHover':                  '#5e6e82',
      '--colorUITupleStroke':                  '#3b4252',
      '--colorUIListItemHovered':              '#434c5e',
      '--colorBulletDefaultFill':              '#5e81ac',
      '--colorBulletDefaultOutline':           '#4c566a',
      '--colorBulletExpandLine':               '#3b4252',
      '--colorBulletExpandLineSelected':       '#434c5e',
      '--colorBulletExpandLineReference':      '#313847',
      '--colorBulletExpandLineHoverBackground':'#434c5e',
      '--colorNavigationCardBackgroundOpen':   '#434c5e',
      '--colorNavigationCardStroke':           '#3b4252',
      '--colorSidebarItemHoverBackground':     '#434c5e',
      '--colorSidebarFadeColor':               '#2e3440',
      '--colorSidebarItemHoverText':           '#eceff4',
      '--colorTooltipBackground':              '#4c566a',
      '--colorTooltipText':                    '#d8dee9',
      '--inlineCode':                          '#a3be8c',
      '--inlineCodeBackground':                '#232830',
      '--scrollbarForeground':                 'rgba(136,192,208,0.2)',
      '--scrollbarForegroundHover':            'rgba(136,192,208,0.4)',
      '--scrollbarForegroundActive':           'rgba(136,192,208,0.6)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.2), 0px 0.75rem 1.5rem rgba(0,0,0,0.3)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.25)',
      '--colorButtonNeutralBackground':        '#3b4252',
      '--colorButtonNeutralStroke':            '#4c566a',
      '--colorButtonNeutralText':              '#9aa8c0',
      '--colorButtonNeutralHoverBackground':   '#434c5e',
    },
  },

  'catppuccin-mocha': {
    id: 'catppuccin-mocha', name: 'Catppuccin Mocha', mode: 'dark',
    preview: ['#1e1e2e', '#cba6f7', '#cdd6f4'],
    vars: {
      '--colorPanelBackground':                '#1e1e2e',
      '--colorPanelBackgroundDimmed':          '#181825',
      '--colorPanelBackgroundHighlighted':     '#313244',
      '--colorPanelBackgroundTransparent':     'rgba(30,30,46,0)',
      '--colorNavigationAltPanelBackground':   '#181825',
      '--colorUIContextMenuBackground':        '#313244',
      '--colorCanvasBackground':               '#11111b',
      '--colorEditorText':                     '#cdd6f4',
      '--colorEditorTextHighlight':            '#e6e9f0',
      '--colorEditorTextMuted':                '#a6adc8',
      '--colorUIText':                         '#bac2de',
      '--colorUITextMuted':                    '#9399b2',
      '--colorUITextDisabled':                 '#585b70',
      '--colorUITextOnHighlight':              '#cdd6f4',
      '--colorLink':                           '#89b4fa',
      '--colorLinkMuted':                      '#74c7ec',
      '--colorHoverLink':                      '#cdd6f4',
      '--colorFocus':                          '#cba6f7',
      '--colorFocusInactive':                  '#45475a',
      '--colorFocusWithin':                    '#7287fd',
      '--colorFocusText':                      '#89b4fa',
      '--colorSelected':                       '#313244',
      '--colorSelectedUnfocused':              '#45475a',
      '--colorTextSelectedUnfocused':          '#585b70',
      '--colorTextHighlightedBackground':      '#45475a',
      '--colorUIStroke':                       '#45475a',
      '--colorUIStrokeSoft':                   '#313244',
      '--colorUIStrokeHover':                  '#585b70',
      '--colorUITupleStroke':                  '#313244',
      '--colorUIListItemHovered':              '#313244',
      '--colorBulletDefaultFill':              '#cba6f7',
      '--colorBulletDefaultOutline':           '#45475a',
      '--colorBulletExpandLine':               '#313244',
      '--colorBulletExpandLineSelected':       '#45475a',
      '--colorBulletExpandLineReference':      '#1e1e2e',
      '--colorBulletExpandLineHoverBackground':'#313244',
      '--colorNavigationCardBackgroundOpen':   '#45475a',
      '--colorNavigationCardStroke':           '#313244',
      '--colorSidebarItemHoverBackground':     '#313244',
      '--colorSidebarFadeColor':               '#1e1e2e',
      '--colorSidebarItemHoverText':           '#e6e9f0',
      '--colorTooltipBackground':              '#45475a',
      '--colorTooltipText':                    '#cdd6f4',
      '--inlineCode':                          '#f38ba8',
      '--inlineCodeBackground':                '#181825',
      '--scrollbarForeground':                 'rgba(203,166,247,0.2)',
      '--scrollbarForegroundHover':            'rgba(203,166,247,0.4)',
      '--scrollbarForegroundActive':           'rgba(203,166,247,0.6)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.3), 0px 0.75rem 1.5rem rgba(0,0,0,0.4)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.3)',
      '--colorButtonNeutralBackground':        '#313244',
      '--colorButtonNeutralStroke':            '#45475a',
      '--colorButtonNeutralText':              '#bac2de',
      '--colorButtonNeutralHoverBackground':   '#45475a',
    },
  },

  'rose-pine': {
    id: 'rose-pine', name: 'Rosé Pine', mode: 'dark',
    preview: ['#191724', '#ebbcba', '#e0def4'],
    vars: {
      '--colorPanelBackground':                '#191724',
      '--colorPanelBackgroundDimmed':          '#1f1d2e',
      '--colorPanelBackgroundHighlighted':     '#26233a',
      '--colorPanelBackgroundTransparent':     'rgba(25,23,36,0)',
      '--colorNavigationAltPanelBackground':   '#1f1d2e',
      '--colorUIContextMenuBackground':        '#26233a',
      '--colorCanvasBackground':               '#16141f',
      '--colorEditorText':                     '#e0def4',
      '--colorEditorTextHighlight':            '#e0def4',
      '--colorEditorTextMuted':                '#908caa',
      '--colorUIText':                         '#9e9bb4',
      '--colorUITextMuted':                    '#6e6a86',
      '--colorUITextDisabled':                 '#524f67',
      '--colorUITextOnHighlight':              '#e0def4',
      '--colorLink':                           '#9ccfd8',
      '--colorLinkMuted':                      '#31748f',
      '--colorHoverLink':                      '#e0def4',
      '--colorFocus':                          '#ebbcba',
      '--colorFocusInactive':                  '#403d52',
      '--colorFocusWithin':                    '#c4a7e7',
      '--colorFocusText':                      '#9ccfd8',
      '--colorSelected':                       '#26233a',
      '--colorSelectedUnfocused':              '#2a273f',
      '--colorTextSelectedUnfocused':          '#403d52',
      '--colorTextHighlightedBackground':      '#2a273f',
      '--colorUIStroke':                       '#403d52',
      '--colorUIStrokeSoft':                   '#26233a',
      '--colorUIStrokeHover':                  '#524f67',
      '--colorUITupleStroke':                  '#26233a',
      '--colorUIListItemHovered':              '#26233a',
      '--colorBulletDefaultFill':              '#ebbcba',
      '--colorBulletDefaultOutline':           '#403d52',
      '--colorBulletExpandLine':               '#26233a',
      '--colorBulletExpandLineSelected':       '#403d52',
      '--colorBulletExpandLineReference':      '#1f1d2e',
      '--colorBulletExpandLineHoverBackground':'#26233a',
      '--colorNavigationCardBackgroundOpen':   '#2a273f',
      '--colorNavigationCardStroke':           '#26233a',
      '--colorSidebarItemHoverBackground':     '#26233a',
      '--colorSidebarFadeColor':               '#191724',
      '--colorSidebarItemHoverText':           '#e0def4',
      '--colorTooltipBackground':              '#403d52',
      '--colorTooltipText':                    '#e0def4',
      '--inlineCode':                          '#eb6f92',
      '--inlineCodeBackground':                '#1f1d2e',
      '--scrollbarForeground':                 'rgba(235,188,186,0.2)',
      '--scrollbarForegroundHover':            'rgba(235,188,186,0.4)',
      '--scrollbarForegroundActive':           'rgba(235,188,186,0.6)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.3), 0px 0.75rem 1.5rem rgba(0,0,0,0.4)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.3)',
      '--colorButtonNeutralBackground':        '#26233a',
      '--colorButtonNeutralStroke':            '#403d52',
      '--colorButtonNeutralText':              '#9e9bb4',
      '--colorButtonNeutralHoverBackground':   '#2a273f',
    },
  },

  'warm-sepia': {
    id: 'warm-sepia', name: 'Warm Sepia', mode: 'light',
    preview: ['#f4ece3', '#9e5a3c', '#3d2b1f'],
    vars: {
      '--colorPanelBackground':                '#f4ece3',
      '--colorPanelBackgroundDimmed':          '#ede4db',
      '--colorPanelBackgroundHighlighted':     '#e8dfd4',
      '--colorPanelBackgroundTransparent':     'rgba(244,236,227,0)',
      '--colorNavigationAltPanelBackground':   '#ede4db',
      '--colorUIContextMenuBackground':        '#faf6f2',
      '--colorCanvasBackground':               '#ede4db',
      '--colorEditorText':                     '#3d2b1f',
      '--colorEditorTextHighlight':            '#2a1a10',
      '--colorEditorTextMuted':                '#7a6454',
      '--colorUIText':                         '#6a5446',
      '--colorUITextMuted':                    '#927a6a',
      '--colorUITextDisabled':                 '#baa898',
      '--colorUITextOnHighlight':              '#3d2b1f',
      '--colorLink':                           '#9e5a3c',
      '--colorLinkMuted':                      '#b57a5a',
      '--colorHoverLink':                      '#2a1a10',
      '--colorFocus':                          '#c06840',
      '--colorFocusInactive':                  '#c4b49a',
      '--colorFocusWithin':                    '#d4a070',
      '--colorFocusText':                      '#9e5a3c',
      '--colorSelected':                       '#e8dfd4',
      '--colorSelectedUnfocused':              '#ddd4c8',
      '--colorTextSelectedUnfocused':          '#c4b49a',
      '--colorTextHighlightedBackground':      '#f0d4b0',
      '--colorUIStroke':                       '#c4b49a',
      '--colorUIStrokeSoft':                   '#d8cfc4',
      '--colorUIStrokeHover':                  '#a89a84',
      '--colorUITupleStroke':                  '#ddd4c8',
      '--colorUIListItemHovered':              '#ddd4c8',
      '--colorBulletDefaultFill':              '#9e5a3c',
      '--colorBulletDefaultOutline':           '#c4b49a',
      '--colorBulletExpandLine':               '#ddd4c8',
      '--colorBulletExpandLineSelected':       '#d0c7bc',
      '--colorBulletExpandLineReference':      '#e8dfd4',
      '--colorBulletExpandLineHoverBackground':'#ddd4c8',
      '--colorNavigationCardBackgroundOpen':   '#ddd4c8',
      '--colorNavigationCardStroke':           '#c4b49a',
      '--colorSidebarItemHoverBackground':     '#ddd4c8',
      '--colorSidebarFadeColor':               '#f4ece3',
      '--colorSidebarItemHoverText':           '#2a1a10',
      '--colorTooltipBackground':              '#6a5446',
      '--colorTooltipText':                    '#f4ece3',
      '--inlineCode':                          '#8b4513',
      '--inlineCodeBackground':                '#e8dfd4',
      '--scrollbarForeground':                 'rgba(158,90,60,0.15)',
      '--scrollbarForegroundHover':            'rgba(158,90,60,0.3)',
      '--scrollbarForegroundActive':           'rgba(158,90,60,0.45)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.04), 0px 0.75rem 1.5rem rgba(0,0,0,0.07)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.06)',
      '--colorButtonNeutralBackground':        '#ede4db',
      '--colorButtonNeutralStroke':            '#c4b49a',
      '--colorButtonNeutralText':              '#6a5446',
      '--colorButtonNeutralHoverBackground':   '#e8dfd4',
    },
  },

  'coffee-professional': {
    id: 'coffee-professional', name: 'CoffeeBuddy Pro', mode: 'light',
    preview: ['#FAF8F5', '#8B6F47', '#2C2420'],
    vars: {
      '--colorPanelBackground':                '#FAF8F5',
      '--colorPanelBackgroundDimmed':          '#F5F2ED',
      '--colorPanelBackgroundHighlighted':     '#EDE8E0',
      '--colorPanelBackgroundTransparent':     'rgba(250,248,245,0)',
      '--colorNavigationAltPanelBackground':   '#F0EBE3',
      '--colorUIContextMenuBackground':        '#F8F5F0',
      '--colorCanvasBackground':               '#EDE8E0',
      '--colorEditorText':                     '#3A3230',
      '--colorEditorTextHighlight':            '#2C2420',
      '--colorEditorTextMuted':                '#7A5C42',
      '--colorUIText':                         '#5C4033',
      '--colorUITextMuted':                    '#8B6F47',
      '--colorUITextDisabled':                 '#C4AE96',
      '--colorUITextOnHighlight':              '#2C2420',
      '--colorLink':                           '#8B6F47',
      '--colorLinkMuted':                      '#A68860',
      '--colorHoverLink':                      '#2C2420',
      '--colorFocus':                          '#8B6F47',
      '--colorFocusInactive':                  '#D4C0A8',
      '--colorFocusWithin':                    '#C4A880',
      '--colorFocusText':                      '#5C4033',
      '--colorSelected':                       '#EDE8E0',
      '--colorSelectedUnfocused':              '#E8E0D4',
      '--colorTextSelectedUnfocused':          '#D4C0A8',
      '--colorTextHighlightedBackground':      '#F4E4C8',
      '--colorUIStroke':                       '#D4BFA8',
      '--colorUIStrokeSoft':                   '#E8E0D4',
      '--colorUIStrokeHover':                  '#B8A48C',
      '--colorUITupleStroke':                  '#E8E0D4',
      '--colorUIListItemHovered':              '#EDE8E0',
      '--colorBulletDefaultFill':              '#8B6F47',
      '--colorBulletDefaultOutline':           '#D4BFA8',
      '--colorBulletExpandLine':               '#E8E0D4',
      '--colorBulletExpandLineSelected':       '#DDD4C8',
      '--colorBulletExpandLineReference':      '#EDE8E0',
      '--colorBulletExpandLineHoverBackground':'#DDD4C8',
      '--colorNavigationCardBackgroundOpen':   '#E8E0D4',
      '--colorNavigationCardStroke':           '#D4BFA8',
      '--colorSidebarItemHoverBackground':     '#EDE8E0',
      '--colorSidebarFadeColor':               '#FAF8F5',
      '--colorSidebarItemHoverText':           '#2C2420',
      '--colorTooltipBackground':              '#5C4033',
      '--colorTooltipText':                    '#FAF8F5',
      '--inlineCode':                          '#7A5C42',
      '--inlineCodeBackground':                '#F0EBE3',
      '--scrollbarForeground':                 'rgba(139,111,71,0.15)',
      '--scrollbarForegroundHover':            'rgba(139,111,71,0.3)',
      '--scrollbarForegroundActive':           'rgba(139,111,71,0.45)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(44,36,32,0.04), 0px 0.75rem 1.5rem rgba(44,36,32,0.07)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(44,36,32,0.07)',
      '--colorButtonNeutralBackground':        '#EDE8E0',
      '--colorButtonNeutralStroke':            '#D4BFA8',
      '--colorButtonNeutralText':              '#5C4033',
      '--colorButtonNeutralHoverBackground':   '#E8E0D4',
    },
  },

  'coffee-dark': {
    id: 'coffee-dark', name: 'CoffeeBuddy Dark', mode: 'dark',
    preview: ['#1A1512', '#D4A574', '#E8DCC8'],
    vars: {
      '--colorPanelBackground':                '#1A1512',
      '--colorPanelBackgroundDimmed':          '#221C18',
      '--colorPanelBackgroundHighlighted':     '#2A2420',
      '--colorPanelBackgroundTransparent':     'rgba(26,21,18,0)',
      '--colorNavigationAltPanelBackground':   '#221C18',
      '--colorUIContextMenuBackground':        '#2A231D',
      '--colorCanvasBackground':               '#130F0C',
      '--colorEditorText':                     '#E0D4C0',
      '--colorEditorTextHighlight':            '#F5E6D3',
      '--colorEditorTextMuted':                '#A88B70',
      '--colorUIText':                         '#C8A884',
      '--colorUITextMuted':                    '#907060',
      '--colorUITextDisabled':                 '#5A4535',
      '--colorUITextOnHighlight':              '#F5E6D3',
      '--colorLink':                           '#E8B87C',
      '--colorLinkMuted':                      '#D4A574',
      '--colorHoverLink':                      '#F5E6D3',
      '--colorFocus':                          '#D4A574',
      '--colorFocusInactive':                  '#4A3828',
      '--colorFocusWithin':                    '#A87845',
      '--colorFocusText':                      '#E8B87C',
      '--colorSelected':                       '#2A231D',
      '--colorSelectedUnfocused':              '#3D3228',
      '--colorTextSelectedUnfocused':          '#4A3828',
      '--colorTextHighlightedBackground':      '#3D3020',
      '--colorUIStroke':                       '#4A3828',
      '--colorUIStrokeSoft':                   '#2A231D',
      '--colorUIStrokeHover':                  '#6A5040',
      '--colorUITupleStroke':                  '#2A231D',
      '--colorUIListItemHovered':              '#2A2420',
      '--colorBulletDefaultFill':              '#D4A574',
      '--colorBulletDefaultOutline':           '#4A3828',
      '--colorBulletExpandLine':               '#2A231D',
      '--colorBulletExpandLineSelected':       '#3D3228',
      '--colorBulletExpandLineReference':      '#1A1512',
      '--colorBulletExpandLineHoverBackground':'#2A231D',
      '--colorNavigationCardBackgroundOpen':   '#3D3228',
      '--colorNavigationCardStroke':           '#2A231D',
      '--colorSidebarItemHoverBackground':     '#2A2420',
      '--colorSidebarFadeColor':               '#1A1512',
      '--colorSidebarItemHoverText':           '#F5E6D3',
      '--colorTooltipBackground':              '#3D3228',
      '--colorTooltipText':                    '#E8DCC8',
      '--inlineCode':                          '#E8A87C',
      '--inlineCodeBackground':                '#2A231D',
      '--scrollbarForeground':                 'rgba(212,165,116,0.2)',
      '--scrollbarForegroundHover':            'rgba(212,165,116,0.4)',
      '--scrollbarForegroundActive':           'rgba(212,165,116,0.6)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.25), 0px 0.75rem 1.5rem rgba(0,0,0,0.4)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.3)',
      '--colorButtonNeutralBackground':        '#2A231D',
      '--colorButtonNeutralStroke':            '#4A3828',
      '--colorButtonNeutralText':              '#C8A884',
      '--colorButtonNeutralHoverBackground':   '#3D3228',
    },
  },

  'charcoal-squashed': {
    id: 'charcoal-squashed', name: 'Charcoal Squashed', mode: 'dark',
    preview: ['#2E3235', '#D3DB90', '#E1E3E2'],
    vars: {
      '--colorPanelBackground':                '#2E3235',
      '--colorPanelBackgroundDimmed':          '#353A3D',
      '--colorPanelBackgroundHighlighted':     '#3D4245',
      '--colorPanelBackgroundTransparent':     'rgba(46,50,53,0)',
      '--colorNavigationAltPanelBackground':   '#272B2E',
      '--colorUIContextMenuBackground':        '#3D4245',
      '--colorCanvasBackground':               '#262A2C',
      '--colorEditorText':                     '#E1E3E2',
      '--colorEditorTextHighlight':            '#EAECED',
      '--colorEditorTextMuted':                '#9AA0A3',
      '--colorUIText':                         '#ABACAF',
      '--colorUITextMuted':                    '#787E81',
      '--colorUITextDisabled':                 '#555A5D',
      '--colorUITextOnHighlight':              '#E1E3E2',
      '--colorLink':                           '#D3DB90',
      '--colorLinkMuted':                      '#B0B870',
      '--colorHoverLink':                      '#EAECED',
      '--colorFocus':                          '#D3DB90',
      '--colorFocusInactive':                  '#464A4D',
      '--colorFocusWithin':                    '#00B9ED',
      '--colorFocusText':                      '#D3DB90',
      '--colorSelected':                       '#353A3D',
      '--colorSelectedUnfocused':              '#3D4245',
      '--colorTextSelectedUnfocused':          '#464A4D',
      '--colorTextHighlightedBackground':      '#3A5A6A',
      '--colorUIStroke':                       '#464A4D',
      '--colorUIStrokeSoft':                   '#353A3D',
      '--colorUIStrokeHover':                  '#5A6063',
      '--colorUITupleStroke':                  '#353A3D',
      '--colorUIListItemHovered':              '#3D4245',
      '--colorBulletDefaultFill':              '#D3DB90',
      '--colorBulletDefaultOutline':           '#464A4D',
      '--colorBulletExpandLine':               '#353A3D',
      '--colorBulletExpandLineSelected':       '#3D4245',
      '--colorBulletExpandLineReference':      '#2E3235',
      '--colorBulletExpandLineHoverBackground':'#3D4245',
      '--colorNavigationCardBackgroundOpen':   '#3D4245',
      '--colorNavigationCardStroke':           '#353A3D',
      '--colorSidebarItemHoverBackground':     '#3D4245',
      '--colorSidebarFadeColor':               '#2E3235',
      '--colorSidebarItemHoverText':           '#EAECED',
      '--colorTooltipBackground':              '#464A4D',
      '--colorTooltipText':                    '#E1E3E2',
      '--inlineCode':                          '#00B9ED',
      '--inlineCodeBackground':                '#272B2E',
      '--scrollbarForeground':                 'rgba(211,219,144,0.2)',
      '--scrollbarForegroundHover':            'rgba(211,219,144,0.4)',
      '--scrollbarForegroundActive':           'rgba(211,219,144,0.6)',
      '--shadowSoft':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.2), 0px 0.75rem 1.5rem rgba(0,0,0,0.32)',
      '--shadowHard':                          '0px 0.1rem 0.1rem rgba(0,0,0,0.25)',
      '--colorButtonNeutralBackground':        '#353A3D',
      '--colorButtonNeutralStroke':            '#464A4D',
      '--colorButtonNeutralText':              '#ABACAF',
      '--colorButtonNeutralHoverBackground':   '#3D4245',
    },
  },

  // ── Add new built-in themes above this line (used by scripts/new-theme.sh) ──
};

// ── CSS builder ───────────────────────────────────────────────────────────────
function buildCSS(theme) {
  if (!theme || !theme.vars || !Object.keys(theme.vars).length) return '';
  const modeSelector = theme.mode === 'light' ? 'html.isLightMode' : 'html.isDarkMode';
  const themeClass   = `.tana-theme-${theme.id}`;
  const declarations = Object.entries(theme.vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `${modeSelector}${themeClass} {\n${declarations}\n}`;
}

module.exports = { THEMES, buildCSS };
